name: CI Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8  # Replace with your desired Python version

    #- name: Install expect
    #  run: sudo apt-get update && sudo apt-get install -y expect
      
    - name: Install dependencies
      run: |
        pip install -r flask_db_app/requirements.txt

    - name: Database setup
      run: |
        python flask_db_app/make_db.py
        python flask_db_app/pop_db.py
        # Set up your database here (e.g., create the test database, apply migrations).

    - name: Run Unit Tests
      run: |
        pytest flask_db_app/test_app.py

    - name: Run flask app
      run: |
        python flask_db_app/app.py

    - name: Stop Flask Server
      run: |
        # Find the Flask server process and send a signal to stop it
        PID=$(pgrep -f "python flask_db_app/app.py")
        if [ -z "$PID" ]; then
          echo "Flask server is not running."
        else
          echo "Stopping Flask server..."
          kill $PID
        fi
  
