name: CI Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8  # Replace with your desired Python version

      
    - name: Install dependencies
      run: |
        #pip install -r flask_db_app/requirements.txt
        pip install poetry
        cd flask_db_app
        poetry install
        cd ..
          
    - name: Database setup
      run: |
        cd flask_db_app
        poetry run python make_db.py
        poetry run python pop_db.py
        cd ..

    - name: Run Unit Tests
      run: |
        cd flask_db_app
        pytest test_app.py
        cd ..

