name: CI Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8  # Replace with your desired Python version

    - name: Install dependencies
      run: |
        pip install -r flask_db_app/requirements.txt

    - name: Database setup
      run: |
        python flask_db_app/make_db.py
        python flask_db_app/pop_db.py
        # Set up your database here (e.g., create the test database, apply migrations).

    - name: Run flask app
      run: |
        chmod +x flask_db_app/expect_script.sh
        ./flask_db_app/expect_script.sh

    - name: Run Unit Tests
      run: |
        pytest flask_db_app/test_app.py
